name: Auto deployment for Azure Container Apps.

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main
      - develop
    paths:
      - "frontend/**"
      - "backend/**"

  # Allow mannually trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  REPOSITORY_NAME: REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")

jobs:
  build:
    runs-on: ubuntu-latest

    # Switch environments depending on branch
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development'}}

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to container registry
        id: acrtoken
        uses: azure/CLI@v1
        with:
          inlineScript: |
            accessToken=$(az acr login -n ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }} --expose-token --query accessToken -o tsv)
            echo ::set-output name=token::$accessToken
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: 00000000-0000-0000-0000-000000000000
          password: ${{ steps.acrtoken.outputs.token }}

      - name: Build and push container image to registry
        run: |
          echo "REPOSITORY_NAME=$(echo ${{ github.repository }} | sed -e "s#.*/##")" >> $GITHUB_ENV

          docker-compose -f ./docker-compose.yml build
          docker tag ${{ env.REPOSITORY_NAME }}-frontend:latest ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_FRONTEND }}:${{ github.sha }}
          docker tag ${{ env.REPOSITORY_NAME }}-backend:latest ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_BACKEND }}:${{ github.sha }}
          docker tag ${{env.REPOSITORY_NAME }}-db:latest ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_DB }}:${{ github.sha }}
          docker push ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_FRONTEND }}:${{ github.sha }}
          docker push ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_BACKEND }}:${{ github.sha }}
          docker push ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_DB }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Switch environments depending on branch
    environment: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'develop' && 'Development'}}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update \
                -n ${{ vars.CONTAINER_NAME_FRONTEND }} \
                -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
                --image ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_FRONTEND }}:${{ github.sha }}
            az containerapp update \
                -n ${{ vars.CONTAINER_NAME_BACKEND }} \
                -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
                --image ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_BACKEND }}:${{ github.sha }}
            az containerapp update \
                -n ${{ vars.CONTAINER_NAME_DB }} \
                -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
                --image ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_NAME_DB }}:${{ github.sha }}
